Solving all tasks in modules 7
js-tasks-ru/nodejs-20210907_snlevchenko pull request #5
Opened 2021-10-06 15:36 UTC by nuykon

2021-10-06 15:37 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-10-07 06:29 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-10-08 08:25 UTC, tadjik1 commented on 07-authentication/01-local/libs/strategies/local.js
> +      await User.findOne({ email }, async (err, user) => {
не смешивайте в одну кучу async/await и коллбеки, такой код очень сложно читать и тем более править.
намного лучше будет
```
const user = await User.findOne();
if (!user) ...
const isValidPwd = await user.checkPassword(password);
...

```

2021-10-08 08:27 UTC, tadjik1 commented on 07-authentication/02-oauth/libs/strategies/authenticate.js
> +  await User.findOne({ email }, async (err, user) => {
комментарий выше применим и сюда тоже

2021-10-08 08:28 UTC, tadjik1 requested changes
@nuykon прекрасные решения, я отметил лишь небольшой стилистический нюанс, который надо поправить. в целом логику вы реализовали на 100% верно

2021-10-08 09:21 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-10-08 09:24 UTC, nuykon commented on 07-authentication/01-local/libs/strategies/local.js
> +      await User.findOne({ email }, async (err, user) => {
поправил

2021-10-08 09:24 UTC, nuykon commented on 07-authentication/02-oauth/libs/strategies/authenticate.js
> +  await User.findOne({ email }, async (err, user) => {
поправил

2021-10-08 09:29 UTC, tadjik1 approved these changes
@nuykon супер 👏

2021-10-08 09:30 UTC, merged